Convert IRC colour codes to minetest colour codes.
kaeza/minetest-irc pull request #41
Opened 2017-05-04 21:50 UTC by red-001

2017-05-06 20:22 UTC, ShadowNinja commented on init.lua
> +chunk(ie)
This can be simplified to `assert(loadfile(modpath.."/hooks.lua"))(ie)`.

2017-05-06 20:49 UTC, kaeza commented on init.lua
> +chunk(ie)
This should be split from this commit, IMHO. It's unrelated to the feature being added.

2017-05-11 23:49 UTC, kaeza requested changes

2017-05-11 23:49 UTC, kaeza commented on hooks.lua
> +		local irc_code = line:match("^(%d+)")
This block would take e.g. "01foo" at the start of the string as an escape sequence.

2017-05-11 23:49 UTC, kaeza commented on hooks.lua
> +	[1] = "black",
You only really need the index for [0]. The others are auto-numbered starting at 1.

2017-05-11 23:49 UTC, kaeza commented on hooks.lua
> +local function convert_colour(text)
Minor nit: `color`.

2017-10-03 16:14 UTC, sofar commented
This seems worth merging, perhaps @kaeza can fix-on-merge or @red-001 red-001 can refresh this?

2018-04-24 03:10 UTC, sofar commented
ping?

2024-12-25 11:40 UTC, SmallJoker commented
No activity in .. uhm. 6 years. Closing.

2024-12-25 11:40 UTC, closed without merging